
services:
  micpy-server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
      - WHISPER_MODEL_SIZE=medium
    restart: unless-stopped